project:
  type: book
  output-dir: docs

book:
  title: "Survival Analysis"
  author: "Michael Foley"
  date: today
  cover-image: images/cover.png
  favicon: favicon.ico
  chapters:
    - index.qmd
    - 01-concepts.qmd
    - 02-km.qmd
    - 03-parametric.qmd
    - 04-cox.qmd
    - 05-discrete-time.qmd
    - 06-ml.qmd
    - 07-case-study.qmd
    - 08-references.qmd

bibliography: references.bib

execute: 
  echo: true
  message: false
  error: false
  warning: false

format:
  html:
    theme: cosmo
    toc-title: "On this page"
    toc-depth: 4
    code-tools: true
    code-overflow: scroll
    code-fold: false
    fig-cap-location: bottom

editor: source

language: 
  code-summary: "Show the code"
